baseURL = "https://oo-infty.netlify.app"
languageCode = "zh-cn"
title = "oo-infty's site"

theme = "paper"

[params]
  color = "linen"

  avatar = "https://cravatar.cn/avatar/f14933f57df2a9ffb229419fa19ce98f?s=512"
  name = "oo-infty"

  disableHLJS = true
  disablePostNavigation = true
  monoDarkIcon = true
  math = true
